[profile.default]
src = "contracts"
out = "out"
libs = ["lib", "dependencies"]
test = "foundry_test"

[dependencies]
forge-std = "foundry-rs/forge-std@v1.14.0"
"@openzeppelin-contracts" = "OpenZeppelin/openzeppelin-contracts@v5.0.2"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
